import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from "react-hot-toast";

import { ThirdwebProvider } from "@thirdweb-dev/react";

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThirdwebProvider activeChain="binance-testnet">
          {children}
          <Toaster></Toaster>
        </ThirdwebProvider>
      </body>
    </html>
  );
}
